import { TemplateConfig } from '@/types/invitation'

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'wedding-sona-v2',
    name: 'Sona',
    category: 'wedding',
    vibe: 'traditional-indian',
    description: 'Modern Indian luxury. Envelope opening, marigold garlands, diya animations, family blessings, 5 event cards. The real thing.',
    previewImage: '/previews/wedding-sona-v2.jpg',
    accentColor: '#C9A84C',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Georgia' },
    tier: 'luxury',
  },
  {
    id: 'wedding-modern-indian',
    name: 'Sona',
    category: 'wedding',
    vibe: 'traditional-indian',
    description: 'Modern Indian luxury. Dark, gold-accented, cinematic. For the couple who wants grandeur without the kitsch.',
    previewImage: '/previews/wedding-modern-indian.jpg',
    accentColor: '#C9A84C',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Georgia' },
    tier: 'luxury',
  },
  {
    id: 'wedding-cinematic',
    name: 'Reel',
    category: 'wedding',
    vibe: 'modern-elegant',
    description: 'Film poster energy. Dramatic full-bleed typography, parallax scenes, feels like a movie trailer for their wedding.',
    previewImage: '/previews/wedding-cinematic.jpg',
    accentColor: '#EFEFEF',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Georgia' },
    tier: 'luxury',
  },
  {
    id: 'wedding-petal',
    name: 'Petal',
    category: 'wedding',
    vibe: 'garden',
    description: 'Warm cream, editorial, romantic. Falling petals, soft light, the smell of rain.',
    previewImage: '/previews/wedding-petal.jpg',
    accentColor: '#C4847A',
    fonts: { display: 'Cormorant Garamond', script: 'Pinyon Script', body: 'Georgia' },
    tier: 'luxury',
  },
  {
    id: 'wedding-cosmos',
    name: 'Cosmos',
    category: 'wedding',
    vibe: 'celestial',
    description: 'Deep space, real parallax star field, constellation lines. For the couple whose love is written in the stars.',
    previewImage: '/previews/wedding-cosmos.jpg',
    accentColor: '#7C3AED',
    fonts: { display: 'Cinzel', script: 'Great Vibes', body: 'Georgia' },
    tier: 'luxury',
  },
  {
    id: 'wedding-modern-elegant',
    name: 'Noir & Gold',
    category: 'wedding',
    vibe: 'modern-elegant',
    description: 'Cinematic dark luxury. For couples who live in black turtlenecks and candlelit dinners.',
    previewImage: '/previews/wedding-modern-elegant.jpg',
    accentColor: '#A16207',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Cormorant Infant' },
    tier: 'luxury',
  },
  {
    id: 'wedding-traditional-indian',
    name: 'Shaadi Rang',
    category: 'wedding',
    vibe: 'traditional-indian',
    description: 'Jewel tones, marigolds, and the warmth of a thousand diyas. Pure Indian soul.',
    previewImage: '/previews/wedding-traditional-indian.jpg',
    accentColor: '#DC2626',
    fonts: { display: 'Tiro Devanagari Hindi', script: 'Pacifico', body: 'Hind' },
    tier: 'luxury',
  },
  {
    id: 'wedding-mountain',
    name: 'Above the Clouds',
    category: 'wedding',
    vibe: 'mountain',
    description: 'Pine, mist, and altitude. For the couple whose love story lives at 8,000 feet.',
    previewImage: '/previews/wedding-mountain.jpg',
    accentColor: '#4B5563',
    fonts: { display: 'Josefin Sans', script: 'Dancing Script', body: 'Lato' },
    tier: 'premium',
  },
  {
    id: 'wedding-beach',
    name: 'Salt & Sundown',
    category: 'wedding',
    vibe: 'beach',
    description: 'Waves, golden hour, and bare feet in the sand. Destination wedding energy.',
    previewImage: '/previews/wedding-beach.jpg',
    accentColor: '#0891B2',
    fonts: { display: 'Abril Fatface', script: 'Pacifico', body: 'Nunito' },
    tier: 'premium',
  },
  {
    id: 'wedding-celestial',
    name: 'Written in Stars',
    category: 'wedding',
    vibe: 'celestial',
    description: 'The universe conspired to bring them together. Deep navy, constellations, cosmic love.',
    previewImage: '/previews/wedding-celestial.jpg',
    accentColor: '#7C3AED',
    fonts: { display: 'Cinzel', script: 'Great Vibes', body: 'Raleway' },
    tier: 'luxury',
  },
  {
    id: 'wedding-garden',
    name: 'Bloom',
    category: 'wedding',
    vibe: 'garden',
    description: 'Wildflowers, soft light, and the smell of rain. Romantic and alive.',
    previewImage: '/previews/wedding-garden.jpg',
    accentColor: '#16A34A',
    fonts: { display: 'Cormorant Garamond', script: 'Pinyon Script', body: 'Lora' },
    tier: 'premium',
  },
  {
    id: 'wedding-royal',
    name: 'The Grand Affair',
    category: 'wedding',
    vibe: 'royal',
    description: 'Palatial. Opulent. The kind of wedding people talk about for decades.',
    previewImage: '/previews/wedding-royal.jpg',
    accentColor: '#B45309',
    fonts: { display: 'IM Fell English', script: 'Pinyon Script', body: 'Crimson Text' },
    tier: 'luxury',
  },
  {
    id: 'birthday-celestial',
    name: 'Another Trip Around the Sun',
    category: 'birthday',
    vibe: 'celestial',
    description: 'A cosmic tribute to a life that keeps expanding. Stars, orbits, and wonder.',
    previewImage: '/previews/birthday-celestial.jpg',
    accentColor: '#7C3AED',
    fonts: { display: 'Cinzel', script: 'Great Vibes', body: 'Raleway' },
    tier: 'luxury',
  },
  {
    id: 'birthday-modern-elegant',
    name: 'The Edit',
    category: 'birthday',
    vibe: 'modern-elegant',
    description: 'Editorial. Curated. A magazine spread dedicated to one extraordinary person.',
    previewImage: '/previews/birthday-modern-elegant.jpg',
    accentColor: '#A16207',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Cormorant Infant' },
    tier: 'luxury',
  },
  {
    id: 'birthday-bohemian',
    name: 'Free Spirit',
    category: 'birthday',
    vibe: 'bohemian',
    description: 'Earthy, wild, and full of life. For the person who lives outside the lines.',
    previewImage: '/previews/birthday-bohemian.jpg',
    accentColor: '#D97706',
    fonts: { display: 'Abril Fatface', script: 'Satisfy', body: 'Nunito' },
    tier: 'premium',
  },
  {
    id: 'birthday-mountain',
    name: 'Summit',
    category: 'birthday',
    vibe: 'mountain',
    description: 'Every year is a peak conquered. For the adventurer who keeps climbing.',
    previewImage: '/previews/birthday-mountain.jpg',
    accentColor: '#4B5563',
    fonts: { display: 'Josefin Sans', script: 'Dancing Script', body: 'Lato' },
    tier: 'premium',
  },
  {
    id: 'birthday-beach',
    name: 'Golden Hour',
    category: 'birthday',
    vibe: 'beach',
    description: 'Sun-soaked, salty, and full of joy. A celebration as warm as the person.',
    previewImage: '/previews/birthday-beach.jpg',
    accentColor: '#F59E0B',
    fonts: { display: 'Abril Fatface', script: 'Pacifico', body: 'Nunito' },
    tier: 'classic',
  },
  {
    id: 'birthday-traditional-indian',
    name: 'Jashn',
    category: 'birthday',
    vibe: 'traditional-indian',
    description: 'Dholak, mithai, and the whole mohalla invited. Pure desi celebration energy.',
    previewImage: '/previews/birthday-traditional-indian.jpg',
    accentColor: '#DC2626',
    fonts: { display: 'Tiro Devanagari Hindi', script: 'Pacifico', body: 'Hind' },
    tier: 'premium',
  },
  {
    id: 'wedding-bohemian',
    name: 'Wild & Free',
    category: 'wedding',
    vibe: 'bohemian',
    description: 'Earthy, wild, and outside the lines. For the couple who lives life on their own terms.',
    previewImage: '/previews/wedding-bohemian.jpg',
    accentColor: '#D97706',
    fonts: { display: 'Abril Fatface', script: 'Satisfy', body: 'Nunito' },
    tier: 'premium',
  },
  {
    id: 'birthday-midnight',
    name: 'Midnight',
    category: 'birthday',
    vibe: 'celestial',
    description: 'Dark, dramatic, and deeply personal. For the person who deserves a night that feels like a film.',
    previewImage: '/previews/birthday-midnight.jpg',
    accentColor: '#7C3AED',
    fonts: { display: 'Cinzel', script: 'Great Vibes', body: 'Raleway' },
    tier: 'luxury',
  },
  {
    id: 'wedding-retro-bollywood',
    name: 'Filmi Shaadi',
    category: 'wedding',
    vibe: 'royal',
    description: 'Vintage Bollywood film poster energy. Dramatic, warm, and unmistakably desi.',
    previewImage: '/previews/wedding-retro-bollywood.jpg',
    accentColor: '#C8860A',
    fonts: { display: 'Playfair Display', script: 'Great Vibes', body: 'Cormorant Infant' },
    tier: 'luxury',
  },
  {
    id: 'wedding-minimalist',
    name: 'The Quiet Luxury',
    category: 'wedding',
    vibe: 'modern-elegant',
    description: 'Pure white space, thin serifs, and nothing else. For the couple who believes less is everything.',
    previewImage: '/previews/wedding-minimalist.jpg',
    accentColor: '#1A1A1A',
    fonts: { display: 'Cormorant Garamond', script: 'Cormorant Garamond', body: 'Raleway' },
    tier: 'luxury',
  },
  {
    id: 'birthday-neon-nights',
    name: 'Neon Nights',
    category: 'birthday',
    vibe: 'celestial',
    description: 'Dark, electric, neon-lit. For the person who parties hard and lives loud.',
    previewImage: '/previews/birthday-neon-nights.jpg',
    accentColor: '#FF006E',
    fonts: { display: 'Josefin Sans', script: 'Josefin Sans', body: 'Josefin Sans' },
    tier: 'premium',
  },
]

export function getTemplate(id: string): TemplateConfig | undefined {
  return TEMPLATES.find(t => t.id === id)
}

export function getTemplatesByCategory(category: 'wedding' | 'birthday'): TemplateConfig[] {
  return TEMPLATES.filter(t => t.category === category)
}
